import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FormDataProvider } from "@/context/FormDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "phonytechs form",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="light">
            <body className={inter.className}>
                <FormDataProvider>{children}</FormDataProvider>
            </body>
        </html>
    );
}
